fun main() {
    print('O')
    print(' ')
    print('X')
    print(' ')
    print('X')
    println()
    print('O')
    print(' ')
    print('X')
    print(' ')
    print('O')
    println()
    print('X')
    print(' ')
    print('O')
    print(' ')
    print('X')
}